export const experienceFlows = {
  analyst: {
    5: {
      entryLabel: 'Browse trusted data',
      screens: [
        {
          kind: 'catalog',
          title: 'Data products',
          subtitle: 'Browse trusted, governed data available in Edu Hub.',
          search: 'student attendance',
          productIds: ['attendance', 'identity', 'calendar'],
          primaryLabel: 'Open Student Attendance',
        },
        {
          kind: 'asset',
          productId: 'attendance',
          primaryLabel: 'Request access',
          secondaryLabel: 'View sample SQL',
        },
        {
          kind: 'form',
          title: 'Request access',
          subtitle: 'Request Student Attendance for a defined analytical purpose.',
          fields: [
            ['Purpose', 'Analyse persistent absenteeism and understand which student groups are most affected.'],
            ['Workspace', 'HQ Analytics Workspace'],
            ['Requested products', 'Student Attendance, Student Identity'],
            ['Access period', '90 days'],
          ],
          primaryLabel: 'Submit request',
        },
        {
          kind: 'workspace',
          title: 'Persistent absenteeism analysis',
          subtitle: 'HQ Analytics Workspace',
          badges: ['2 products connected', 'Access approved'],
          code: `SELECT\n  s.school_code,\n  s.level,\n  COUNT_IF(a.attendance_status = 'ABSENT') AS absent_days\nFROM student_attendance a\nJOIN student_identity s USING (student_id)\nGROUP BY 1, 2\nORDER BY absent_days DESC;`,
          resultColumns: ['school_code', 'level', 'absent_days'],
          resultRows: [
            ['SCH-014', 'Secondary 1', '438'],
            ['SCH-022', 'Secondary 2', '391'],
            ['SCH-009', 'Secondary 1', '372'],
          ],
          assistant: 'I can explain fields, generate SQL or check whether your joins use governed keys.',
        },
      ],
    },
    7: {
      entryLabel: 'Start from an analysis use case',
      screens: [
        {
          kind: 'intent',
          eyebrow: 'Analysis setup',
          title: 'What are you trying to analyse?',
          subtitle: 'Describe the business question. Edu Hub will recommend governed data and a starting workspace.',
          prompt: 'I want to analyse persistent absenteeism and understand which student groups are most affected.',
          suggestions: ['Attendance trends by cohort', 'Academic results over time', 'Student support indicators'],
          primaryLabel: 'Build analysis setup',
        },
        {
          kind: 'plan',
          title: 'Recommended analysis setup',
          subtitle: 'Edu Hub prepared the minimum useful starting point.',
          rows: [
            ['Primary data', 'Student Attendance', 'Daily attendance, absence categories and latecoming', 'SDP'],
            ['Join context', 'Student Identity', 'School, class, level and student profile', 'SDP'],
            ['Metric', 'Persistent absence v3', 'MOE-governed definition', 'Governed'],
            ['Workspace', 'HQ Analytics Workspace', 'SQL + Python starter notebook', 'Ready'],
          ],
          checks: [
            ['Student Identity', 'Already granted'],
            ['Student Attendance', 'Owner approval'],
            ['Sensitive notes', 'Not included'],
          ],
          primaryLabel: 'Set up analysis',
          secondaryLabel: 'Adjust setup',
        },
        {
          kind: 'progress',
          title: 'Setting up your analysis',
          subtitle: 'Edu Hub is coordinating access and workspace setup.',
          tasks: [
            ['Analysis intent captured', 'Persistent absenteeism by student group'],
            ['Student Identity entitlement checked', 'Existing HQ access reused'],
            ['Student Attendance approval', 'Submitted to Student Data Domain owner'],
            ['Workspace preparation', 'Notebook, joins and metric definitions'],
          ],
          summary: [['Data products', '2'], ['Governed metrics', '1'], ['Manual extracts', '0']],
          primaryLabel: 'Simulate approval',
        },
        {
          kind: 'workspace',
          title: 'Persistent absenteeism',
          subtitle: 'Starter analysis prepared from your approved setup.',
          badges: ['2 SDPs connected', 'Persistent absence v3'],
          code: `-- Prepared by Edu Hub. Review and edit before use.\nWITH attendance AS (\n  SELECT * FROM student_attendance\n),\nstudents AS (\n  SELECT student_id, school_code, level\n  FROM student_identity\n)\nSELECT level,\n       persistent_absence_rate(attendance.*) AS rate\nFROM attendance\nJOIN students USING (student_id)\nGROUP BY level;`,
          chart: 'cohort',
          assistant: 'I prepared the governed metric and recommended join. You can change the breakdown before running.',
        },
      ],
    },
    9: {
      entryLabel: 'Start from analytical intent',
      screens: [
        {
          kind: 'intent',
          eyebrow: 'Analytical intent',
          title: 'What do you want to understand?',
          subtitle: 'Ask in analytical terms. Edu Hub will prepare a reviewable data and analysis plan.',
          prompt: 'Which student groups show the strongest increase in persistent absenteeism this term, and where should I investigate further?',
          suggestions: ['Compare current vs previous term', 'Highlight unusual cohorts', 'Show only trusted data'],
          primaryLabel: 'Prepare analysis',
        },
        {
          kind: 'plan',
          title: 'Proposed analysis',
          subtitle: 'Review the approach before Edu Hub creates the workspace.',
          rows: [
            ['Question', 'Largest term-on-term increase', 'Rank cohorts and identify concentration', 'Interpreted'],
            ['Data', 'Student Attendance + Student Identity', '11 fields selected, 9 unnecessary fields excluded', 'Approved'],
            ['Metric', 'Persistent absence v3', 'Current term vs prior term', 'Governed'],
            ['Quality', '2 school feeds delayed', 'Those results will be marked provisional', 'Warning'],
          ],
          checks: [
            ['HQ analysis scope', 'Pass'],
            ['Counselling notes', 'Excluded'],
            ['Student-level drill-down', 'Allowed'],
          ],
          primaryLabel: 'Create workspace',
          secondaryLabel: 'Edit plan',
        },
        {
          kind: 'workspace',
          title: 'Persistent absenteeism',
          subtitle: 'Generated starting analysis. Review before running.',
          badges: ['Policy checked', '2 feeds delayed'],
          code: `-- Generated from your approved analysis plan\nWITH current_term AS (...),\n     prior_term AS (...)\nSELECT cohort_group,\n       current_rate - prior_rate AS change_pp\nFROM current_term\nJOIN prior_term USING (cohort_group)\nORDER BY change_pp DESC;`,
          resultColumns: ['Cohort', 'Change', 'Status'],
          resultRows: [
            ['Lower secondary', '+1.8 pp', 'Current'],
            ['Selected programme group', '+1.4 pp', 'Current'],
            ['School cluster A', '+1.3 pp', '2 feeds provisional'],
          ],
          assistant: 'I generated this from Persistent Absence v3. Two school feeds are delayed and no counselling-note content is included.',
        },
      ],
    },
    11: {
      entryLabel: 'Start from the question itself',
      screens: [
        {
          kind: 'intent',
          eyebrow: 'Analysis',
          title: 'Ask a question about MOE data',
          subtitle: 'Edu Hub assembles the authorised evidence while keeping data, definitions and assumptions inspectable.',
          prompt: 'Which student groups show the strongest increase in persistent absenteeism this term, and what evidence supports that?',
          suggestions: ['Show evidence', 'Compare with previous term', 'Explain uncertainty'],
          primaryLabel: 'Analyse',
        },
        {
          kind: 'answer',
          title: 'Persistent absenteeism',
          headline: 'Increase is concentrated in a small number of lower-secondary cohorts',
          body: 'The strongest term-on-term increases are concentrated in selected lower-secondary cohorts across a small set of schools. The MOE-wide rate is relatively stable. Two school feeds are delayed today, so their latest values are marked provisional.',
          metrics: [['Largest cohort change', '+1.8 pp'], ['Schools driving change', '4'], ['Delayed feeds', '2']],
          chart: 'cohort',
          evidence: [
            ['Student Attendance', 'Standard data product · healthy'],
            ['Student Identity', 'Standard data product · healthy'],
            ['Persistent absence v3', 'Governed definition'],
            ['Data quality', '2 delayed school feeds flagged'],
            ['Excluded', 'No counselling-note content used'],
          ],
          primaryLabel: 'Open reproducible analysis',
          secondaryLabel: 'Ask follow-up',
        },
        {
          kind: 'workspace',
          title: 'Reproducible analysis',
          subtitle: 'Everything behind the answer is inspectable and rerunnable.',
          badges: ['Reproducible', '2 SDPs', 'Definition v3'],
          code: `-- Snapshot generated for this answer\n-- Sources: Student Attendance, Student Identity\n-- Metric: Persistent Absence v3\n-- Quality: 2 source feeds provisional\n\nSELECT cohort_group,\n       current_rate,\n       prior_rate,\n       current_rate - prior_rate AS change_pp\nFROM governed_persistent_absence_comparison;`,
          assistant: 'This is the exact analysis used for the previous answer. You can edit, rerun or inspect lineage.',
        },
      ],
    },
  },

  business: {
    5: {
      entryLabel: 'Browse trusted business experiences',
      screens: [
        {
          kind: 'discover',
          title: 'Discover',
          subtitle: 'Find trusted dashboards and self-service experiences.',
          search: 'attendance trends',
          items: [
            ['Dashboard', 'Student Attendance Overview', 'School and cohort attendance trends for authorised users.', 'Trusted'],
            ['Self-service', 'Persistent Absence Explorer', 'Explore persistent absence using governed definitions.', 'Trusted'],
            ['Data product', 'Student Attendance', 'Technical data product for analysts and systems.', 'Technical'],
          ],
          primaryLabel: 'Open Student Attendance Overview',
        },
        {
          kind: 'dashboardDetail',
          title: 'Student Attendance Overview',
          subtitle: 'Trusted business view for monitoring attendance.',
          primaryLabel: 'Request access',
        },
        {
          kind: 'dashboard',
          title: 'Student Attendance Overview',
          subtitle: 'Attendance v3 · Updated today, 6:04 PM',
          metrics: [['Attendance rate', '92.8%'], ['Persistent absence', '4.7%'], ['Schools above threshold', '12'], ['Data freshness', 'Today 6:04 PM']],
          chart: 'monthly',
          table: [
            ['School cluster A', '+2.6 pp'],
            ['School cluster B', '+2.2 pp'],
            ['Lower secondary', '+1.8 pp'],
          ],
        },
      ],
    },
    7: {
      entryLabel: 'Start from a business need',
      screens: [
        {
          kind: 'intent',
          eyebrow: 'Business question',
          title: 'What do you need to understand?',
          subtitle: 'Describe the business need. Edu Hub will recommend the right trusted experience.',
          prompt: 'I want to know which schools or student groups may need attention based on attendance trends.',
          suggestions: ['Attendance trends', 'Persistent absence', 'Changes since last term'],
          primaryLabel: 'Show recommendations',
        },
        {
          kind: 'recommendations',
          title: 'Recommended experiences',
          subtitle: 'Start with the simplest trusted way to answer the question.',
          items: [
            ['Best match', 'Persistent Absence Explorer', 'Compare schools and cohorts using the governed persistent absence definition.', 'Access granted'],
            ['Dashboard', 'Student Attendance Overview', 'High-level monitoring and trend view.', 'Trusted'],
            ['Self-service Q&A', 'Ask attendance data', 'Use natural language for follow-up questions.', 'Available'],
            ['Technical option', 'Student Attendance SDP', 'For analysts who need lower-level data.', 'Optional'],
          ],
          primaryLabel: 'Open best match',
        },
        {
          kind: 'dashboard',
          title: 'Persistent Absence Explorer',
          subtitle: 'Persistent absence v3 · Your HQ access scope',
          metrics: [['Attendance rate', '92.8%'], ['Persistent absence', '4.7%'], ['Schools above threshold', '12'], ['Definition', 'v3']],
          chart: 'school',
          table: [
            ['Which cohorts drive the increase?', 'Suggested follow-up'],
            ['What changed since last term?', 'Suggested follow-up'],
            ['Which schools account for most change?', 'Suggested follow-up'],
          ],
        },
      ],
    },
    9: {
      entryLabel: 'Ask a governed business question',
      screens: [
        {
          kind: 'intent',
          eyebrow: 'Business Q&A',
          title: 'Ask a question about your area',
          subtitle: 'Answers use governed definitions and your authorised scope.',
          prompt: 'Which schools have seen a meaningful increase in persistent absenteeism this term?',
          suggestions: ['Explain the calculation', 'Show only current data', 'Compare with previous term'],
          primaryLabel: 'Ask',
        },
        {
          kind: 'answer',
          title: 'Attendance Q&A',
          headline: '12 schools show a material increase this term',
          body: 'Four schools account for most of the overall increase. Two schools have delayed source feeds today, so their latest values are marked provisional.',
          metrics: [['Schools above threshold', '12'], ['Largest change', '+2.6 pp'], ['Provisional', '2']],
          chart: 'school',
          evidence: [
            ['Metric', 'Persistent absence v3'],
            ['Comparison', 'Current term vs previous term'],
            ['Scope', 'Your HQ access applied'],
            ['Quality', '2 delayed feeds flagged'],
          ],
          primaryLabel: 'Show schools',
          secondaryLabel: 'Explain calculation',
        },
        {
          kind: 'table',
          title: 'School drill-down',
          subtitle: 'Same definition, comparison period and access scope.',
          columns: ['School group', 'Persistent absence', 'Change', 'Data status'],
          rows: [
            ['School cluster A', '6.2%', '+2.6 pp', 'Current'],
            ['School cluster B', '5.8%', '+2.2 pp', 'Current'],
            ['School cluster C', '5.1%', '+1.4 pp', 'Provisional'],
          ],
        },
      ],
    },
    11: {
      entryLabel: 'Receive a contextual data briefing',
      screens: [
        {
          kind: 'intent',
          eyebrow: 'Your data briefing',
          title: 'What do you need to know?',
          subtitle: 'Ask in business language. Edu Hub keeps context, definitions and permissions throughout the conversation.',
          prompt: 'Give me a briefing on persistent absenteeism this term. What has changed and where should I look?',
          suggestions: ['What changed since last month?', 'Show affected cohorts', 'Show supporting evidence'],
          primaryLabel: 'Create briefing',
        },
        {
          kind: 'answer',
          title: 'Attendance briefing',
          headline: 'Overall attendance is stable, but increases are concentrated in a small set of cohorts',
          body: 'Persistent absence is broadly stable at MOE level. The main change is a concentration of higher absence in selected lower-secondary cohorts across four schools. Two delayed feeds are excluded from strong conclusions.',
          metrics: [['MOE-level change', '+0.2 pp'], ['Concentrated schools', '4'], ['Provisional feeds', '2']],
          chart: 'cohort',
          evidence: [
            ['Governed metrics', 'Attendance rate, Persistent absence v3'],
            ['Products', 'Student Attendance, Student Identity'],
            ['Scope', 'HQ authorised'],
            ['Lineage', 'Available for every statement'],
          ],
          primaryLabel: 'Ask follow-up',
        },
        {
          kind: 'conversation',
          title: 'Attendance briefing',
          subtitle: 'Conversation context preserved.',
          messages: [
            ['user', 'What changed since last month?'],
            ['assistant', 'The MOE-wide rate changed little. Most of the shift is concentrated in lower-secondary cohorts across four schools.'],
            ['user', 'Show me the evidence behind those four schools.'],
            ['assistant', 'I can open the school comparison with the same definition, time window and access scope.'],
          ],
          context: [['Metric', 'Persistent absence v3'], ['Comparison', 'Current term vs prior term'], ['Scope', 'HQ']],
        },
      ],
    },
  },

  system: {
    5: {
      entryLabel: 'Browse stable data contracts',
      screens: [
        {
          kind: 'contract',
          title: 'Student Attendance',
          subtitle: 'Stable contract for application consumption.',
          productId: 'attendance',
          delivery: ['REST API', 'Direct query', 'Managed file'],
          primaryLabel: 'Choose REST API',
        },
        {
          kind: 'api',
          title: 'REST API',
          subtitle: 'Student Attendance v2.3',
          code: `GET /data-products/student-attendance/v2/records?student_id={id}\nAuthorization: Bearer <workload-token>\n\n200 OK\n{\n  "student_id": "S123",\n  "attendance_date": "2026-09-27",\n  "attendance_status": "PRESENT",\n  "freshness_timestamp": "2026-09-27T17:58:00+08:00"\n}`,
          facts: [['Auth', 'Workload identity'], ['Rate limit', '600 req/min'], ['Sandbox', 'Available'], ['Non-AWS', 'Supported']],
          primaryLabel: 'Request system access',
        },
        {
          kind: 'form',
          title: 'Request system access',
          subtitle: 'Register the consuming system and approved purpose.',
          fields: [
            ['Consuming system', 'Student Support App'],
            ['Purpose', 'Display current attendance information to authorised case officers.'],
            ['Environment', 'Production'],
            ['Delivery', 'REST API'],
          ],
          primaryLabel: 'Submit request',
        },
        {
          kind: 'api',
          title: 'Student Support App',
          subtitle: 'Integration console · Sandbox ready',
          code: `const response = await fetch(\n  "/data-products/student-attendance/v2/records",\n  { headers: { Authorization: \`Bearer ${'${token}'}\` } }\n);\n\n// Contract: student-attendance@2.3`,
          facts: [['Sandbox', 'Ready'], ['Workload identity', 'Ready'], ['Production entitlement', 'Approved'], ['Contract tests', '6 available']],
        },
      ],
    },
    7: {
      entryLabel: 'Start from the application need',
      screens: [
        {
          kind: 'intent',
          eyebrow: 'Integration assistant',
          title: 'What does your application need?',
          subtitle: 'Describe the business data need and operating constraints. Edu Hub will recommend the data products and delivery route.',
          prompt: 'Our application needs current student identity and attendance data daily. It runs outside AWS and must not depend on Redshift connectivity.',
          suggestions: ['Daily batch', 'Non-AWS consumer', 'Needs sandbox'],
          primaryLabel: 'Recommend integration',
        },
        {
          kind: 'plan',
          title: 'Recommended integration',
          subtitle: 'Based on your application requirement.',
          rows: [
            ['Data product', 'Student Identity', 'Core identifiers and enrolment context', 'Required'],
            ['Data product', 'Student Attendance', 'Daily attendance and absence status', 'Required'],
            ['Delivery', 'REST API', 'Best fit for a non-AWS application', 'Recommended'],
            ['Testing', 'Sandbox + contract tests', 'Included in subscription', 'Included'],
          ],
          checks: [['Products', '2'], ['Interface', 'REST API'], ['Environment', 'External cloud']],
          primaryLabel: 'Subscribe',
          secondaryLabel: 'Adjust requirement',
        },
        {
          kind: 'progress',
          title: 'Provisioning subscription',
          subtitle: 'Student Support App',
          tasks: [
            ['Data owner approval', 'Student Identity and Attendance approved'],
            ['Workload identity', 'Service principal created'],
            ['Sandbox entitlement', 'Ready'],
            ['Production API entitlement', 'Provisioning'],
          ],
          summary: [['API contract', 'v2.3'], ['Contract tests', '6'], ['Telemetry', 'Enabled']],
          primaryLabel: 'Continue to integration',
        },
        {
          kind: 'api',
          title: 'Student Support App',
          subtitle: 'Integration package',
          code: `import { EduHubClient } from "@moe/eduhub";\n\nconst client = new EduHubClient({\n  products: [\n    "student-identity@1",\n    "student-attendance@2.3"\n  ]\n});\n\nconst attendance = await client.studentAttendance.get({ studentId });`,
          facts: [['Sandbox', 'Ready'], ['Production', 'Ready'], ['Observability', 'Connected'], ['Breaking-change alerts', 'On']],
        },
      ],
    },
    9: {
      entryLabel: 'Describe service requirements',
      screens: [
        {
          kind: 'intent',
          eyebrow: 'Integration assistant',
          title: 'Describe the application requirement',
          subtitle: 'State what the app needs. Edu Hub will derive the minimal contract and a suitable delivery pattern.',
          prompt: 'We need student identity and same-day attendance. Volume is moderate, the consumer is outside AWS, and the app should tolerate source delays.',
          suggestions: ['Same-day freshness', 'Cross-platform', 'Graceful degradation'],
          primaryLabel: 'Generate contract',
        },
        {
          kind: 'plan',
          title: 'Proposed consumer contract',
          subtitle: 'Review before generation.',
          rows: [
            ['Products', 'Student Identity + Student Attendance', 'Mapped from business requirement', '2 SDPs'],
            ['Fields', '11 required', '7 unnecessary fields excluded', 'Minimised'],
            ['Delivery', 'REST API', 'Cross-platform and moderate volume', 'Recommended'],
            ['Resilience', 'Freshness indicator + last-known-good', 'Makes source delays explicit', 'Added'],
          ],
          checks: [['Sensitive fields', 'Pass'], ['Non-AWS', 'Supported'], ['Breaking changes', 'None']],
          primaryLabel: 'Generate integration',
          secondaryLabel: 'Edit fields',
        },
        {
          kind: 'api',
          title: 'Generated integration',
          subtitle: 'Student Support App',
          code: `const client = new EduHubClient({\n  contract: "student-attendance@2.3",\n  includeFreshness: true,\n  fallback: "last-known-good"\n});\n\nconst response = await client.getAttendance({ studentId });\n\nif (response.isStale) {\n  showFreshnessWarning(response.freshness);\n}`,
          facts: [['SDK scaffold', 'Ready'], ['Contract tests', '8'], ['Observability hooks', 'Included'], ['Policy checks', 'Passed']],
        },
      ],
    },
    11: {
      entryLabel: 'Bind to a business-level contract',
      screens: [
        {
          kind: 'consumerHealth',
          title: 'Student Support App',
          subtitle: 'Production consumer',
          contracts: [
            ['Student Attendance', 'Stable contract · v2 compatible · within SLO'],
            ['Student Identity', 'Stable contract · v1 compatible · within SLO'],
          ],
          facts: [['Implementation', 'Managed'], ['Storage dependency', 'None exposed'], ['SLO', '99.7%']],
          primaryLabel: 'View latest platform change',
        },
        {
          kind: 'change',
          title: 'Platform change completed',
          subtitle: 'No consumer action required.',
          message: 'The underlying attendance implementation was migrated while the Student Attendance business contract remained unchanged.',
          metrics: [['Consumer code changes', '0'], ['Contract tests', '47 / 47'], ['Downtime', '0 min'], ['SLO', '99.7%']],
          primaryLabel: 'View compatibility',
        },
        {
          kind: 'table',
          title: 'Compatibility and consumer impact',
          subtitle: 'Changes are evaluated against registered consumers before release.',
          columns: ['Consumer', 'Contract', 'Latest test', 'Breaking impact'],
          rows: [
            ['Student Support App', 'v2.3', '47 passed', 'None'],
            ['MOEinfo', 'v2.2', '36 passed', 'None'],
            ['KM2', 'v2.3', '41 passed', 'None'],
          ],
        },
      ],
    },
  },

  partner: {
    5: {
      entryLabel: 'Start from an approved data request',
      screens: [
        {
          kind: 'form',
          title: 'New data-sharing request',
          subtitle: 'Register the approved purpose before selecting data.',
          fields: [
            ['Partner organisation', 'Example Programme Partner'],
            ['Approved purpose', 'Deliver and evaluate an approved student support programme.'],
            ['MOE sponsor', 'Programme owner'],
            ['Access period', '6 months'],
          ],
          primaryLabel: 'Continue',
        },
        {
          kind: 'table',
          title: 'Data package',
          subtitle: 'Review the minimum data proposed for the approved purpose.',
          columns: ['Field', 'Use', 'Decision'],
          rows: [
            ['Pseudonymous participant ID', 'Link programme records', 'Included'],
            ['School code', 'Programme delivery context', 'Included'],
            ['Attendance band', 'Programme evaluation', 'Included'],
            ['Counselling notes', 'Not required', 'Excluded'],
          ],
          primaryLabel: 'Submit for approval',
        },
        {
          kind: 'progress',
          title: 'Partner access ready',
          subtitle: 'Example Programme Partner',
          tasks: [
            ['Purpose approved', 'Programme owner'],
            ['Data minimisation reviewed', '3 approved fields'],
            ['Partner identity verified', 'Organisation account active'],
            ['Secure delivery enabled', 'Access expires automatically in 6 months'],
          ],
          summary: [['Approved fields', '3'], ['Expiry', '180 days'], ['Audit logging', 'On']],
        },
      ],
    },
    7: {
      entryLabel: 'Start from an approved project',
      screens: [
        {
          kind: 'projects',
          title: 'Partner projects',
          subtitle: 'Approved MOE data-sharing workspaces.',
          projects: [
            ['Student Support Programme', 'Active project', 'Monthly programme evaluation workspace.', '45 days to review'],
            ['Research collaboration', 'Pending', 'Awaiting MOE purpose approval.', 'Pending'],
            ['Example Programme Partner', 'Organisation', 'Verified organisation profile.', 'Verified'],
          ],
          primaryLabel: 'Open Student Support Programme',
        },
        {
          kind: 'intent',
          eyebrow: 'Project setup',
          title: 'What does this project need to achieve?',
          subtitle: 'Edu Hub will recommend the minimum secure data interaction for the approved outcome.',
          prompt: 'We need to identify programme participants and receive a monthly attendance indicator for programme evaluation.',
          suggestions: ['Reuse existing agreement', 'Use synthetic test data', 'Avoid local downloads'],
          primaryLabel: 'Design access',
        },
        {
          kind: 'plan',
          title: 'Recommended project workspace',
          subtitle: 'Designed to meet the purpose with less raw data exposure.',
          rows: [
            ['Identity', 'Pseudonymous participant list', 'No unnecessary direct identifiers', 'Required'],
            ['Outcome data', 'Monthly attendance indicator', 'Aggregated instead of daily raw records', 'Required'],
            ['Development', 'Synthetic test file', 'Available before production access', 'Available'],
            ['Access', 'Secure partner workspace', 'Avoid local raw-data downloads', 'Recommended'],
          ],
          checks: [['Purpose', 'Programme evaluation'], ['Expiry', '180 days'], ['Audit', 'Enabled']],
          primaryLabel: 'Provision workspace',
        },
        {
          kind: 'controlled',
          title: 'Project workspace',
          subtitle: 'Student Support Programme',
          metrics: [['Approved data views', '2'], ['Secure workspace', '1'], ['Days to expiry', '164']],
          chart: 'monthly',
          controls: [['Purpose bound', 'Programme evaluation only'], ['Audit', 'All activity logged'], ['Downloads', 'Restricted to approved outputs']],
        },
      ],
    },
    9: {
      entryLabel: 'State the approved outcome',
      screens: [
        {
          kind: 'intent',
          eyebrow: 'Data minimisation assistant',
          title: 'What outcome does the project need?',
          subtitle: 'Edu Hub will propose the least data needed to achieve the approved purpose.',
          prompt: 'Evaluate whether the programme improves attendance among participating students without needing detailed daily records.',
          suggestions: ['Use monthly metrics', 'Remove direct identifiers', 'Keep work inside MOE'],
          primaryLabel: 'Propose data interaction',
        },
        {
          kind: 'plan',
          title: 'Minimum sufficient data interaction',
          subtitle: 'Review the proposed safeguards.',
          rows: [
            ['Identity', 'Pseudonymous participant key', 'Direct identifiers removed', 'Minimised'],
            ['Attendance', 'Monthly attendance rate', 'Daily raw records not required', 'Aggregated'],
            ['Comparison', 'Approved aggregate cohort', 'Supports evaluation purpose', 'Approved'],
            ['Excluded', 'Counselling notes, offence details, full identifiers', 'Not needed for purpose', 'Excluded'],
          ],
          checks: [['De-identification', 'Applied'], ['Raw export', 'Disabled'], ['Expiry', 'Project end']],
          primaryLabel: 'Create controlled workspace',
        },
        {
          kind: 'controlled',
          title: 'Controlled evaluation workspace',
          subtitle: 'Student Support Programme',
          metrics: [['Participants', '842'], ['Approved fields', '5'], ['Raw downloads', '0'], ['Days remaining', '164']],
          chart: 'monthly',
          controls: [['Purpose bound', 'Programme evaluation only'], ['Audit', 'All queries logged'], ['Export', 'Raw export disabled']],
        },
      ],
    },
    11: {
      entryLabel: 'Ask for the approved outcome',
      screens: [
        {
          kind: 'intent',
          eyebrow: 'Purpose-bound analysis',
          title: 'What approved outcome do you need?',
          subtitle: 'Edu Hub will choose the least-exposing interaction that can satisfy it.',
          prompt: 'We need to evaluate whether programme participation is associated with improved attendance over six months.',
          suggestions: ['Avoid raw exports', 'Use controlled comparison', 'Keep identifiers pseudonymous'],
          primaryLabel: 'Create evaluation',
        },
        {
          kind: 'answer',
          title: 'Programme evaluation',
          headline: 'A controlled comparison is sufficient for the approved outcome',
          body: 'Edu Hub can provide a secure comparison environment using pseudonymous participants, monthly attendance metrics and an approved aggregate comparison cohort. Daily raw attendance and direct identifiers do not need to leave MOE.',
          metrics: [['Raw exports', '0'], ['Approved measures', '3'], ['Expiry', '180d']],
          chart: 'monthly',
          evidence: [
            ['Direct identifiers', 'Excluded'],
            ['Daily raw attendance', 'Not exposed'],
            ['Purpose', 'Bound to programme evaluation'],
            ['Audit', 'Every query logged'],
          ],
          primaryLabel: 'Open controlled analysis',
        },
        {
          kind: 'controlled',
          title: 'Controlled analysis',
          subtitle: 'Only the approved evaluation interaction is available.',
          metrics: [['Participant change', '+1.4 pp'], ['Comparison cohort', '+0.3 pp'], ['Raw record access', 'None']],
          chart: 'monthly',
          controls: [['Purpose', 'Programme evaluation'], ['Expiry', '180 days'], ['Export', 'Disabled'], ['Audit', 'Complete']],
        },
      ],
    },
  },
}

export const personaMeta = {
  analyst: {
    label: 'Analyst',
    role: 'HQ Analyst',
    nav: ['Home', 'Data products', 'Analytics', 'Workspace', 'Data requests'],
    search: 'Search data, notebooks, dashboards and more…',
  },
  business: {
    label: 'Business',
    role: 'Business Officer',
    nav: ['Home', 'Insights', 'Dashboards', 'Ask Edu Hub', 'Saved views'],
    search: 'Search dashboards, insights and business terms…',
  },
  system: {
    label: 'System',
    role: 'Application Developer',
    nav: ['Home', 'Data products', 'Developer', 'Consumers', 'Subscriptions'],
    search: 'Search contracts, APIs, consumers and subscriptions…',
  },
  partner: {
    label: 'External partner',
    role: 'External Partner',
    nav: ['Home', 'Projects', 'Secure workspace', 'Agreements', 'Support'],
    search: 'Search approved projects and workspaces…',
  },
}
