export const resultsProduct = {
  id:'results', name:'Student Academic Results', type:'Standard data product', lifecycle:'Certified', version:'v1.2',
  owner:'Academic Data Domain', steward:'Academic Results Steward', freshness:'Daily by 6 PM', updated:'Today, 5:58 PM', lastValidated:'Today, 6:03 PM', trust:'Warning: 2 delayed schools', classification:'Sensitive', coverage:'Authorised schools; 2 submissions delayed', quality:'98.6% checks passed', authoritative:'Yes',
  description:'Governed final academic results by subject, level, school and year. Synthetic prototype records only.',
  source:'School Results System → validation → Edu Hub', definition:'Subject pass rate v1: students meeting the pass standard divided by students with valid final results. Compare changes in percentage points.', allowedUse:'Approved internal analysis and registered application consumption. Partners receive purpose-specific controlled aggregates only.',
  fields:[['student_id','STRING','Governed identity key','Sensitive','Not null'],['school_code','STRING','School reference','Internal','Reference list'],['subject','STRING','Approved subject code','Internal','Reference list'],['level','STRING','Education level','Internal','Accepted values'],['academic_year','INTEGER','Assessment year','Internal','Valid year'],['passed','BOOLEAN','Meets subject pass standard','Sensitive','Final results only'],['result_status','STRING','FINAL or PROVISIONAL','Internal','Accepted values'],['validated_at','TIMESTAMP','Latest validated source time','Internal','Not null'],['freshness_status','STRING','current or stale','Internal','Contract metadata']],
  deliveries:[['REST API','/v1/student-academic-results','Daily by 6 PM','Registered applications','99.5% monthly'],['Direct query','edu_hub.student_academic_results','Daily by 6 PM','Approved workspaces','99.5% monthly'],['Managed file','Secure managed delivery','Daily 6:15 PM','Approved batch consumers','99.0% monthly']],
  versions:[['v1.2','Current','15 Sep 2026','Add freshness metadata; backward compatible','31 Mar 2027'],['v1.1','Supported','10 Jun 2026','Approved subject codes','31 Dec 2026'],['v1.0','Deprecated','18 Feb 2026','Initial contract; migrate before retirement','31 Oct 2026']],
  consumers:[['Results Support App','REST API','v1.2','Production','Today 5:59 PM'],['MOEinfo','Direct query','v1.1','Production','Today 6:01 PM'],['KM2','REST API','v1.2','Production','Today 5:57 PM'],['HQ Analytics','Direct query','v1.2','Analytics','Today 6:02 PM']],
  lineage:[['School Results System','Source','School-approved final results','Warning: 2 delayed'],['Results validation','Transform','Subject codes, duplicates and finality','Healthy'],['Student Academic Results v1.2','Product','Certified business contract','Monitored'],['HQ Analytics / registered apps','Consumption','Policy and freshness attached','Monitored']],
  qualityChecks:[['Freshness','Daily by 6 PM','School I/J delayed','Warning'],['Completeness','All expected schools','8 of 10 current','Warning'],['Subject codes','Approved list','100%','Pass'],['Unique student-subject-year','No duplicate final result','100%','Pass'],['Finality','Exclude provisional results','Applied','Pass']],
  permissions:[['HQ Analyst','Approved fields','Purpose + workspace','Allowed'],['Business Officer','Aggregate results only','Authorised schools','Allowed'],['Registered application','Contracted minimum fields','Workload identity + entitlement','Allowed'],['External partner','No raw marks or direct identifiers','Approved purpose + expiry','Restricted']],
  sampleRows:[['STU-•••812','SCH-A','Mathematics','Secondary 2','2026','true','FINAL','Today 5:58 PM','current'],['STU-•••044','SCH-B','English','Secondary 1','2026','true','FINAL','Today 5:58 PM','current']],
}
